### ISSUE TITLE
Retention fails on very large databases

### ISSUE THREAD

**Issue by pbirokas** [Icinga/icingadb#618]
## Describe the bug

Bug is created from this Icingadb community thread:
https://community.icinga.com/t/icingadb-keeps-growing-to-absurd-size/12038/8

The icingadb is growing to no end, so I tried with retention for the databases:

```
# cat /etc/icingadb/config.yml |grep -v "# "

database:
  type: mysql
  host: localhost
  database: icingadb
  user: icingadb
  password: 

redis:
  host: localhost

logging:
  options:
    database: debug
    retention: debug

retention:
  history-days: 30
  sla-days: 30
  options:
    acknowledgement: 30
    comment: 30
    downtime: 30
    flapping: 30
    notification: 30
    state: 30
```

The database was to this time very large:
```
-rw-rw---- 1 mysql mysql  29G Jul 18 11:28 sla_history_state.ibd
-rw-rw---- 1 mysql mysql  34G Jul 18 11:28 state_history.ibd
-rw-rw---- 1 mysql mysql  52G Jul 18 11:28 history.ibd
[root@icinga icingadb]# ll -rSh /var/lib/mysql/icingadb/   
```

After a restart of of the icingadb.service I got from time to time this error and the icingadb service stops:

```
Jul 18 15:42:49 icinga icingadb[132922]: Error 1206: The total number of locks exceeds the lock table size
                                         can't perform "DELETE FROM sla_history_state WHERE environment_id = :environment_id AND event_time < :time\nORDER BY event_time LIMIT 5000"
                                         github.com/icinga/icingadb/internal.CantPerformQuery
                                                 github.com/icinga/icingadb/internal/internal.go:30
                                         github.com/icinga/icingadb/pkg/icingadb.(*DB).CleanupOlderThan
                                                 github.com/icinga/icingadb/pkg/icingadb/cleanup.go:53
                                         github.com/icinga/icingadb/pkg/icingadb/history.(*Retention).Start.func1
                                                 github.com/icinga/icingadb/pkg/icingadb/history/retention.go:189
                                         github.com/icinga/icingadb/pkg/periodic.Start.func1
                                                 github.com/icinga/icingadb/pkg/periodic/periodic.go:78
                                         runtime.goexit
                                                 runtime/asm_amd64.s:1594
Jul 18 15:42:49 icinga systemd[1]: icingadb.service: Main process exited, code=exited, status=1/FAILURE
Jul 18 15:42:49 icinga systemd[1]: icingadb.service: Failed with result 'exit-code'.
```

## Your Environment

Include as many relevant details about the environment you experienced the problem in

    Icinga DB Web version: 1.0.2
    Icinga Web 2 version: 2.11.4
    Web browser: Chrome 113
    Icinga 2 version: r2.13.7-1
    Icinga DB version : v1.1.0
    PHP version used : 7.2.24
    Server operating system and version: Rocky Linux release 8.8 (Green Obsidian)

-------------------------------------------------

As a workaround I added those suggested parameters to my mariadb config:

```
# /etc/my.cnf.d/mariadb-server.cnf
[mysqld]
innodb_buffer_pool_chunk_size=536870912
innodb_buffer_pool_instances=4
innodb_buffer_pool_size=2147483648
```

**Comment by julianbrost** [comment]
Did Icinga DB manage to get your history down to 30 days? So when this error happened, was this still in the phase where the unlimited history was reduced down to 30 days?

Can you please try the following in the configuration? This will start the history cleanup routine more frequently (unless it's still running at that time):

```yaml
retention:
  history-days: 30
  sla-days: 30
  interval: 1m
  #count: 500
```

Now if you leave this running for a few minutes, you should see the "Cleaning up historical data for category [...] from table [...] older than [...]" log messages (keep the debug logging enabled for that) more often if there is only about 30 days of history in the database and it just deletes what just got older than 30 days. If you don't see the messages repeat after a few minutes, it's probably still busy with removing history entries that are way older than 30 days.

You can also try to set the `count` option I've included as a comment in the config snippet. This controls how many old history entries are deleted in a single query (the default being 5000), maybe setting this to a lower value helps in making the queries more reliable (it might come at a performance penalty though, i.e. reduce the number of rows that can be deleted per second).
