### ISSUE TITLE
strange behaviour of guessing ip address

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingadb#652]
## Describe the bug

I have this icingadb.yml:
```
database:
  host: localhost
  database: icingadb
  user: icingadb
...
redis:
  host: localhost

```

it's a server with 3 networkcards, and the mysql permissions are granted to icingadb@localhost and icingadb@127.0.0.1.
icingadb tries to pad the ip address of one interface to the hostname, here for example 172.21.23.99

any idea whats wrong here? there is a similar issue #555, that's why I granted permissions to icingadb@127.0.0.1 as well

Best regards nicolas

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: 1.1.1
* Icinga 2 version: 2.14
* Operating System and version: Ubuntu 20.04

## Additional context
<img width="749" alt="Screenshot 2023-10-02 170751" src="https://github.com/Icinga/icingadb/assets/29682206/0f4b7051-abd2-42f2-a1b5-ed7cfa0ffe7e">
