### ISSUE TITLE
DOC: Issue icingadb-migrate tool

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingadb#949]
## Describe the bug

As due to a Migration Setup from a customer the lack of more documentation for the icingadb-migrate tool for the database connections was eye opening 

## To Reproduce

Due to the Setup of the database credentials where the data is migrated from and to.
There seems no clear Entry in the Documentation for the key/value parts in the example yaml.

Example:
```
ido:
  type: mysql # or "pgsql" for PostgreSQL
  host: 127.0.0.1
  #port: 3306
  database: icinga
  user: icinga
  password: CHANGEME
  #tls: false
  #cert: <Path to TLS client certificate>
  #key: <Path to TLS private key>
  #ca: <Path to TLS CA certificate>
  #insecure: false
```
The Description to what tls true,false or insecure true,false has an impact on would be greatly appreciated in the official Documentation.

Also the tool itself has no verbose output in case of incorrect set credentials or not correct tls handling it just states ```.. database connecting``` no error / no message just a running process with no hint that something should happen.

## Expected behavior

In case of incorrect set credentials a verbose output that shows the connection attempt from the icingadb-migrate tool would be helpful as well as a debug output if the tls connection is broken or denied instead of stating a ```database connecting```

Also a description what the insecure parameter does like curl -k would be helpful in the documentation.

A Debug Option would be very nice or at least a logfile where the connection and the background steps are shown that can break would be helpful for finding a reason why the connection to the database or some migration data errors occur.

## Your Environment

* Icinga DB version: latest
* Icinga 2 version: latest

## Additional context

tls certificate chain broken will not be shown, when trying to connect to database with certificates
wrong credentials will not be shown in an output when trying to connect to a database
No helpful output when an error occurs , no verbose option, no logfile option for deeper insight
